### ISSUE TITLE
Link to `solana.com/nft`  is dead

### ISSUE THREAD

**Issue by mudream4869** [NaturalSelectionLabs/Unidata#1]
This link `https://solana.com/nft/` is dead.

https://github.com/DIYgod/Unidata/blob/main/docs/README.md?plain=1#L54

Should it be `https://solana.com/developers/nfts` ?

**Comment by DIYgod** [comment]
Oh, that's right, thanks! I'll change it later, or you can feel free to submit a pr if you like
