### ISSUE TITLE
Build*

### ISSUE THREAD

**Issue by acoolstraw** [NaturalSelectionLabs/Unidata#5]
idk what repo is the correct one because you have like 30 but it's spelled Build not Buidl
![image](https://user-images.githubusercontent.com/45886986/178041581-0ff6bb48-567e-49e5-bb48-5849ff5b135c.png)

**Comment by DIYgod** [comment]
It's a special word that is specific to Web3 https://cryptowallet.com/glossary/buidl/

**Comment by acoolstraw** [comment]
that's not a word, and it's really unprofessional

**Comment by HenryQW** [comment]
it's a Web3 glossary, like gm, fren.

**Comment by acoolstraw** [comment]
does gm mean good morning? and isn't fren a comfy 4chan thing?

**Comment by acoolstraw** [comment]
> fren (plural frens) Pronunciation spelling of friend. (alt-right, Internet slang) A fellow, a comrade. (Internet slang) A white nationalist; fascist; far-right supporter.
yikes!

**Comment by HenryQW** [comment]
aren't buidl, hodl web3 things then?

**Comment by acoolstraw** [comment]
very rude way to shrug off a spelling correction

**Comment by acoolstraw** [comment]
I'm not ignorant, I just don't like spelling mistakes
