### ISSUE TITLE
feat:Use unidata in Next.js

### ISSUE THREAD

**Issue by CoderMageFox** [NaturalSelectionLabs/Unidata#6]
Q:
Since I want to use unidata on the Vercel App of Next.js, the introduction method in the document is not applicable. (The lodash used by unidata in ESM mode, which will cause NextJs to recognize errors. For details, please refer to: https://github.com/vercel/next.js/issues/25454)

My solution is to add https://www.npmjs.com/package/next-transpile-modules,
and configure it in next.config.js:

`const withTM = require('next-transpile-modules')(['unidata.js']);
module.exports = withTM({
  webpack(cfg, { dev, isServer }) {
  //next config
  },
})`

Could I make a pr and add it to the document?

**Comment by DIYgod** [comment]
Thank you very much for your report, but I have already changed `lodash` to `lodash-es` in `v0.6.2`, please try to update it to see if there are still problems.

**Comment by CoderMageFox** [comment]
> Thank you very much for your report, but I have already changed `lodash` to `lodash-es` in `v0.6.2`, please try to update it to see if there are still problems.

Okay.
